org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.fromEnv=JAVA_HOME
org.gradle.configuration-cache=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
